version: '3'

services:
  auth-ms:
    build:
      context: ./
      dockerfile: Dockerfile.prod
      args:
        - AUTH_DATABASE_URL=${AUTH_DATABASE_URL}
    image: fmyersdev/auth-ms:latest
    environment:
      - PORT=${PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
